### ISSUE TITLE
Code in master branch and few more minor things on README file

### ISSUE THREAD

**Issue by authorjapps** [BeTheCodeWithYou/springboot#1]
@BeTheCodeWithYou , Looks great now. We are just creating the tweet message so that other find this repo very very useful and easily find things. 

Couple of things if you could take care in this repo, would be really nice. They are minor ones anyway: 
+ Current branch is `API-SpringData-H2DB-ZeroCode-mvn`
  + Can you merge to `master` - Because befualt landing page will be always `master`
+ Update the README file with 
  + Env switching details
  + Link to the steps for build pipeline and Fail-Fast best practices (probably the medium blog will help here)
+ Steps for maven build
  + Build via Gradle
  + Build by POM
+ Steps viewing reports
  + Searching/Filtering for a Test failure
  + Searching for a particular text to find the UUID of the test step, then trace the actual request/response/assertions in the `target/log` file.
+ And anything useful you can think of please 
  + This [comment](https://github.com/authorjapps/spring-boot-integration-test/issues/6#issuecomment-432010065) has got few of your suggestions.

fyi-
Current landing page is : https://github.com/BeTheCodeWithYou/springboot
(this wil be good after you merge your recent code to master) 👍

**Comment by BeTheCodeWithYou** [comment]
Hi @authorjapps ,

All above comments addressed except "Build via Gradle" point, because "gradle clean build" is not updating the target folder properly hence I didn't add that change yet.

created a new repo ( SpringBoot-ZeroCode-Integration ) and merged all changes to master. Please review and close the ticket.

https://github.com/BeTheCodeWithYou/SpringBoot-ZeroCode-Integration

Have a great time guys. thanks a lot.

**Comment by authorjapps** [comment]
Hey mate, all looking great! Thank for your time. We should **close** this ticket now. 
It's better to bring up a `Wiki Page(s)` under this repo and link it form the README page and it will become much more easier to add/update information there(no need of commit n push every time).
Thanks again for your hard work 🙏
